# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e4cf3eba45e1ffa8762a78e8591d5b2a86793e16040807a46f799fa959f0138890e172ca0b4bfe678c52a24d4b02d425ada0eed082c50ec7d080c5124bbed6f

test:
  secret_key_base: 6c14b8d5ae5332fe58ba4cc3063ada506be0d62ee0d7cd6a7e58f57b278a07334be0d3a8483f13dab959c9cd4c6cbae04358ef4a7662dfe8ec8d6fdea4a46aab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
